# Generated by Django 5.0.6 on 2024-05-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=200)),
                ('invited', models.DateTimeField(verbose_name='date published')),
                ('serviced', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
