# Generated by Django 5.0.6 on 2024-05-09 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuetab',
            name='data_reg',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='queuetab',
            name='ticket_b',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='queuetab',
            name='time_reg',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
