# Generated by Django 5.0.6 on 2024-05-09 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0003_alter_queuetab_invited_alter_queuetab_serviced_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuetab',
            name='ticket_b',
        ),
        migrations.AlterField(
            model_name='queuetab',
            name='data_reg',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='queuetab',
            name='serviced',
            field=models.DateTimeField(verbose_name='Дата и время завершения обслуживания клиента'),
        ),
        migrations.AlterField(
            model_name='queuetab',
            name='ticket',
            field=models.CharField(max_length=200, verbose_name='Талон'),
        ),
        migrations.AlterField(
            model_name='queuetab',
            name='time_reg',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Время'),
        ),
    ]
