# Generated by Django 5.0.6 on 2024-05-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0005_alter_queuetab_data_reg_alter_queuetab_invited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetab',
            name='invited',
            field=models.DateTimeField(verbose_name='Клиент приглашён'),
        ),
    ]
