# Generated by Django 5.0.6 on 2024-05-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0006_alter_queuetab_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetab',
            name='invited',
            field=models.DateTimeField(null=True, verbose_name='Клиент приглашён'),
        ),
        migrations.AlterField(
            model_name='queuetab',
            name='serviced',
            field=models.DateTimeField(null=True, verbose_name='Обслуживание завершено'),
        ),
    ]
